### PR TITLE
Fixed the SimpulationRTPrograms

### PR DESCRIPTION
**Pull request by dythya**
- Updated the output
   - Updated to run on Python 3

### CODE REVIEW

**Review by rhysmdnz — DISMISSED** [review]

**Comment by dythya** [comment]
Modified it so it now runs on all examples non blacklisted.

**Review by rhysmdnz — CHANGES_REQUESTED** [review]
Need to fix testing failures on windows

**Comment by dythya** [comment]
The windows tests run slower so wall clock actually had values :-)

**Comment by rhysmdnz** [comment]
execution speed should not be affecting the test output in tests where we are comparing output

**Review by rhysmdnz — APPROVED** [review]

**Pull request merged**
